### ISSUE TITLE
opensuse/leap:15.1: Error in sourced command file

### ISSUE THREAD

**Issue by nkaretnikov** [crash-python/crash-python#42]
Installation:
```
# zypper addrepo https://download.opensuse.org/repositories/home:/jeff_mahoney:/crash-python/openSUSE_Leap_15.1/home:jeff_mahoney:crash-python.repo

# zypper --gpg-auto-import-keys refresh
# zypper install -y crash-python
```

Command output:
```
# pycrash vmlinux core
/tmp/crash.pIEbvQ/gdbinit:2: Error in sourced command file:
No symbol table is loaded.  Use the "file" command.
(gdb) file vmlinux
Reading symbols from vmlinux...
(gdb) source /tmp/crash.pIEbvQ/gdbinit
/tmp/crash.pIEbvQ/gdbinit:2: Error in sourced command file:
No symbol "build" in current context.
```

Am I doing something wrong? The same files work fine with `crash`:

```
# file core
core: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'BOOT_IMAGE=/boot/vmlinuz root=LABEL=cloudimg-rootfs ro console=t'

# file vmlinux
vmlinux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=4ca54976c8c5fd98ff8af290c5774ed2cc41b02e, with debug_info, not stripped
```

**Comment by jeffmahoney** [comment]
You're not doing anything wrong.  The problem is that I've updated crash-python-gdb to gdb 9.1, which includes a variant of the build-id patches that the openSUSE gdb packages had. It eliminated the 'build-id-verbose' command, which the crash-python used to use.  Crash-python is also updated but it's failing static checks due to updated tools in that area. I ran out of time on Friday to investigate what the build service is doing that I'm not, since the tool versions appear to be the same.

**Comment by jeffmahoney** [comment]
The problem turned out to be an older version of mypy on my system masking the packaged version.  The fixes were simple and I've pushed them. Working packages are available on OBS now.

**Comment by jeffmahoney** [comment]
BTW, the spec file for crash-python-gdb on OBS was broken until this afternoon.  It omitted applying two patches. One was obvious: It would take ages to complete "Loading tasks....". The other one would hit if you encountered a NotAvailableError. If you have an older version of the RPM, you should update it with a build from today.
